# Generated by Django 3.1 on 2020-12-08 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spinningmills', '0001_initial'),
        ('weavers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice', models.FileField(upload_to='')),
                ('invoice_name', models.CharField(max_length=20, verbose_name='Nombre de Factura')),
                ('shipping_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('shipping_schedule', models.IntegerField(choices=[(1, 'AM'), (2, 'PM')], default=1, verbose_name='Horario de envío')),
                ('order_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pedido')),
                ('order_status', models.IntegerField(choices=[(1, 'Recibido'), (2, 'Unidad Asignada'), (3, 'Recojo Exitoso'), (4, 'Entrega Exitosa')], default=1, verbose_name='Estado del Pedido')),
                ('order_enabled', models.IntegerField(default=1, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('spinningmills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spinningmills.spinningmills')),
                ('weavers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weavers.weavers')),
            ],
        ),
    ]
