# Generated by Django 3.1 on 2020-12-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
