# Generated by Django 3.1 on 2020-12-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('orderdetail_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de Producto')),
                ('number_bag', models.IntegerField(default=0, verbose_name='Nro Bolsas')),
                ('amount_kg', models.IntegerField(default=0, verbose_name='Cantidad Kg')),
                ('orderdetail_enabled', models.IntegerField(default=1, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
        ),
    ]
