# Generated by Django 3.1 on 2020-12-08 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orderdetail', '0001_initial'),
        ('orders', '0001_initial'),
        ('yarntype', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='yarntype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yarntype.yarntype'),
        ),
    ]
