# Generated by Django 3.1 on 2020-12-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderdetail', '0002_auto_20201208_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='amount_kg',
            field=models.FloatField(default=0.0, verbose_name='Cantidad Kg'),
        ),
    ]
