# Generated by Django 3.1 on 2020-11-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weavers',
            fields=[
                ('weavers_id', models.AutoField(primary_key=True, serialize=False)),
                ('weavers_document', models.CharField(max_length=20, verbose_name='Nro. Documento')),
                ('business_name', models.CharField(max_length=100, verbose_name='Razón Social')),
                ('fiscal_address', models.CharField(max_length=200, verbose_name='Dirección Fiscal')),
                ('delivery_address', models.CharField(max_length=200, verbose_name='Dirección de Entrega')),
                ('weavers_name', models.CharField(max_length=30, verbose_name='Nombres')),
                ('weavers_lastname', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('weavers_phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Teléfono')),
                ('weavers_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('weavers_enabled', models.IntegerField(default=1, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
        ),
    ]
